function M = dynamics_M(in1,in2,l_L,m_L,m_Q,g,in7)
%DYNAMICS_M
%    M = DYNAMICS_M(IN1,IN2,L_L,M_L,M_Q,G,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Jan-2018 13:44:52

I_x = in2(:,1);
I_y = in2(:,2);
I_z = in2(:,3);
p_S_B_1 = in7(:,1);
p_S_B_2 = in7(:,2);
p_S_B_3 = in7(:,3);
phi_L = in1(:,7);
phi_Q = in1(:,4);
theta_Q = in1(:,5);
t2 = m_L+m_Q;
t3 = p_S_B_2.^2;
t4 = sin(theta_Q);
t5 = p_S_B_3.^2;
t6 = cos(phi_Q);
t7 = cos(theta_Q);
t8 = sin(phi_Q);
t9 = p_S_B_2.*t6;
t10 = t9-p_S_B_3.*t8;
t11 = t6.^2;
t12 = t11-1.0;
t13 = phi_Q.*2.0;
t14 = sin(t13);
t15 = -I_x.*t4-m_L.*t3.*t4-m_L.*t4.*t5-m_L.*p_S_B_1.*p_S_B_3.*t6.*t7-m_L.*p_S_B_1.*p_S_B_2.*t7.*t8;
t16 = I_y.*t7.*t14.*(1.0./2.0);
t17 = m_L.*t5.*t7.*t14.*(1.0./2.0);
t18 = m_L.*p_S_B_1.*p_S_B_2.*t4.*t6;
t19 = cos(t13);
t20 = t16+t17+t18-I_z.*t7.*t14.*(1.0./2.0)-m_L.*t3.*t7.*t14.*(1.0./2.0)-m_L.*p_S_B_1.*p_S_B_3.*t4.*t8-m_L.*p_S_B_2.*p_S_B_3.*t7.*t19;
t21 = m_L.*t3;
t22 = m_L.*t5;
t23 = t7.^2;
t24 = p_S_B_1.^2;
t25 = l_L.^2;
t26 = cos(phi_L);
M = reshape([t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,I_x+t21+t22,-m_L.*p_S_B_1.*t10,t15,0.0,0.0,0.0,0.0,0.0,-m_L.*p_S_B_1.*t10,I_y.*t11-I_z.*t12+m_L.*t24-m_L.*t3.*t12+m_L.*t5.*t11+m_L.*p_S_B_2.*p_S_B_3.*t14,t20,0.0,0.0,0.0,0.0,0.0,t15,t20,I_x+t21+t22-I_x.*t23+I_y.*t23-I_y.*t11.*t23+I_z.*t11.*t23-m_L.*t3.*t23+m_L.*t23.*t24+m_L.*t3.*t11.*t23-m_L.*t5.*t11.*t23+m_L.*p_S_B_1.*p_S_B_3.*t4.*t6.*t7.*2.0+m_L.*p_S_B_1.*p_S_B_2.*t4.*t7.*t8.*2.0-m_L.*p_S_B_2.*p_S_B_3.*t6.*t8.*t23.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,m_L.*t25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,m_L.*t25.*t26.^2],[8,8]);
